"""Add ActionLog model

Revision ID: 1abf92dcabbf
Revises: f16dc1e1266a
Create Date: 2025-04-18 10:51:30.968370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1abf92dcabbf'
down_revision = 'f16dc1e1266a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('entity', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_reset_token', type_='unique')
        batch_op.drop_column('verification_token')
        batch_op.drop_column('email')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('reset_token')
        batch_op.drop_column('reset_token_expiration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token_expiration', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('verification_token', sa.VARCHAR(length=120), nullable=True))
        batch_op.create_unique_constraint('uq_user_reset_token', ['reset_token'])

    op.drop_table('action_log')
    # ### end Alembic commands ###
