"""Fresh start - clean initial migration

Revision ID: 7551f7346387
Revises: 
Create Date: 2025-04-17 16:36:28.206526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7551f7346387'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model_number', sa.String(length=50), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.Column('is_misc', sa.Boolean(), nullable=True),
    sa.Column('appliance_type', sa.String(length=50), nullable=True),
    sa.Column('order_status', sa.String(length=50), nullable=True),
    sa.Column('order_link', sa.String(length=255), nullable=True),
    sa.Column('tracking_number', sa.String(length=50), nullable=True),
    sa.Column('estimated_delivery', sa.Date(), nullable=True),
    sa.Column('delivered_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_number')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('verification_token')
    )
    op.create_table('order_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('purchased_quantity', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('tracking_number', sa.String(length=50), nullable=True),
    sa.Column('estimated_delivery', sa.Date(), nullable=True),
    sa.Column('delivered_date', sa.Date(), nullable=True),
    sa.Column('expense_line', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_history')
    op.drop_table('user')
    op.drop_table('part')
    # ### end Alembic commands ###
